package translation.translationprocesses;

import translation.readers.csconfigreaders.CSConfiguration;
import utilities.LogUtil;

/**
 * Concrete translator for generating an XML representation of a layered composite service.
 * @author Jyotsana Gupta
 */
public class XMLCSTranslator implements CompositeServiceTranslator
{
	/**
	 * Method for translating a given layered composite service into an XML representation.
	 * @param 	compSvcConfig	Composite service configuration containing information required for the translation
	 * @param 	logger			Logging utility object for logging error or status messages to a text file
	 * @return	Complete name and path of the XML file generated by this translator
	 */
	public String generateFormalLangCode(CSConfiguration compSvcConfig, LogUtil logger)
	{
		return null;
	}
}